=== davl3232/JerseyREST/JerseyServer/src/main/java/co/edu/javeriana/webservices/resources/articlesSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="article" type="article" />

	<xs:element name="author" type="author" />

	<xs:element name="peercheck" type="peercheck" />

	<xs:complexType name="peercheck">
		<xs:sequence>
			<xs:element ref="article" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="article">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="authors">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="author" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:long" use="required" />
	</xs:complexType>

	<xs:complexType name="author">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:long" use="required" />
	</xs:complexType>
</xs:schema>

=== davl3232/JerseyREST/JerseyServer/data/articles.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<<<<<<< HEAD
<peercheck xsi:schemaLocation="data/articlesSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <article id="0">
        <title>Programación avanzada en c++</title>
        <authors>
            <author id="1">
                <name>Juan Manuel</name>
                <surname>Sánchez Lozano</surname>
            </author>
            <author id="2">
                <name>Sergio</name>
                <surname>Forero Gómez</surname>
            </author>
        </authors>
    </article>
    <article id="2">
        <title>Nuevo título</title>
        <authors>
            <author id="3">
                <name>David</name>
                <surname>Villamizar Lizcano</surname>
            </author>
            <author id="4">
                <name>Sebastian</name>
                <surname>Bobadilla</surname>
            </author>
            <author id="5">
                <name>Carlos</name>
                <surname>Parra</surname>
            </author>
        </authors>
    </article>
    <article id="3">
        <title>Análisis de algoritmos - Programación dinamica</title>
        <authors>
            <author id="3">
                <name>David Alonso</name>
                <surname>Villamizar Lizcano</surname>
            </author>
            <author id="2">
                <name>Sergio</name>
                <surname>Forero Gómez</surname>
            </author>
        </authors>
    </article>
    <article id="4">
        <title>Nuevo artículo</title>
        <authors>
            <author id="5">
                <name>Carlos</name>
                <surname>Parra</surname>
            </author>
        </authors>
    </article>
    <article id="5">
        <title>Nuevo artículo 2</title>
        <authors>
            <author id="5">
                <name>Carlos</name>
                <surname>Parra</surname>
            </author>
            <author id="5">
                <name>Carlos</name>
                <surname>Parra</surname>
            </author>
        </authors>
    </article>
</peercheck>
=======
<peercheck>
	<article id="0">
		<title>Programación avanzada en c++</title>
		<authors>
			<author id="1">
				<name>Juan Manuel</name>
				<surname>Sánchez Lozano</surname>
			</author>
			<author id="2">
				<name>Sergio</name>
				<surname>Forero Gómez</surname>
			</author>
		</authors>
	</article>
	<article id="1">
		<title>Web services, SOAP o REST</title>
		<authors>
			<author id="3">
				<name>David</name>
				<surname>Villamizar Lizcano</surname>
			</author>
			<author id="4">
				<name>Sebastian</name>
				<surname>Bobadilla</surname>
			</author>
			<author id="1">
				<name>Juan Manuel</name>
				<surname>Sánchez Lozano</surname>
			</author>
		</authors>
	</article>
	<article id="2">
		<title>Programación en la web, PHP</title>
		<authors>
			<author id="3">
				<name>David</name>
				<surname>Villamizar Lizcano</surname>
			</author>
			<author id="4">
				<name>Sebastian</name>
				<surname>Bobadilla</surname>
			</author>
		</authors>
	</article>
	<article id="3">
		<title>Análisis de algoritmos - Programación dinamica</title>
		<authors>
			<author id="3">
				<name>David</name>
				<surname>Villamizar Lizcano</surname>
			</author>
			<author id="2">
				<name>Sergio</name>
				<surname>Forero Gómez</surname>
			</author>
		</authors>
	</article>
</peercheck>
>>>>>>> 3356906960b485fccfec55b98765df6693bc2977
